apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: buildboard-ingress
  labels:
    app: buildboard
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "buildboard-ip"
    networking.gke.io/managed-certificates: "buildboard-cert"
spec:
  rules:
  - host: buildboard.dhamari.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: buildboard-service
            port:
              number: 80